### ISSUE TITLE
This should be a derivation in nixpkgs

### ISSUE THREAD

**Issue by wmertens** [craigmbooth/nix-dependency-visualizer#2]
It would be nice to be able to do `nix-shell -p nix-visualize` for some quick analysis…

**Comment by ghuntley** [comment]
Agreed.

**Comment by nikolaishields** [comment]
I also agree with this issue.
I'd be happy to contribute, are there any contribution guidelines to keep in mind?

**Comment by henrirosten** [comment]
`nix-visualize` is now available in nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/package-management/nix-visualize/default.nix
